on:
  push:
    branches:
    - main
    - feature/*

  pull_request:
    branches:
    - main
    - feature/*

  workflow_dispatch:

jobs:
  my_job:
    name: CI
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4 
 
